/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QDev.com.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author cricr
 */
public class GUI_Admin extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Admin
     */
    public GUI_Admin() {
        initComponents();

        //El Menú desplegable inicia como invisble.
        jP_MenuDesplegable.setVisible(false);
        jB_Help.setVisible(false);
        jB_UserMng.setVisible(false);
        jB_LogOut.setVisible(false);
        //Al igual que el botón para ocultarlo después.
        btn_closeMenu.setVisible(false);

        //Asignación de los manejadores de eventos.
        btn_menu.addActionListener(new OpenMenu());
        btn_closeMenu.addActionListener(new CloseMenu());
        jB_LogOut.addActionListener(new LogOut());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3_LogoFrutalito = new javax.swing.JLabel();
        jLabel4_Titulo = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_closeMenu = new javax.swing.JButton();
        jP_MenuDesplegable = new javax.swing.JPanel();
        jB_UserMng = new javax.swing.JButton();
        jB_Help = new javax.swing.JButton();
        jB_LogOut = new javax.swing.JButton();
        btn_AdministrarUsuarios = new javax.swing.JButton();
        btn_PedidoMateriaPrima = new javax.swing.JButton();
        btn_Produccion = new javax.swing.JButton();
        jLabel1_Up = new javax.swing.JLabel();
        jLabel2_FondoHelados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP-El Frutalito");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3_LogoFrutalito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Logo_Frutalito01.png"))); // NOI18N
        getContentPane().add(jLabel3_LogoFrutalito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4_Titulo.setFont(new java.awt.Font("Kristen ITC", 0, 36)); // NOI18N
        jLabel4_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_Titulo.setText("Bienvenido");
        jLabel4_Titulo.setMaximumSize(new java.awt.Dimension(392, 87));
        jLabel4_Titulo.setMinimumSize(new java.awt.Dimension(392, 87));
        jLabel4_Titulo.setPreferredSize(new java.awt.Dimension(392, 87));
        getContentPane().add(jLabel4_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image_Menu.png"))); // NOI18N
        btn_menu.setBorder(null);
        btn_menu.setContentAreaFilled(false);
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 50));

        btn_closeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image-CloseMenu.png"))); // NOI18N
        btn_closeMenu.setBorder(null);
        btn_closeMenu.setContentAreaFilled(false);
        getContentPane().add(btn_closeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 50));

        jB_UserMng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image_GestionarUsuarios.png"))); // NOI18N
        jB_UserMng.setText("Gestionar Usuarios");
        jB_UserMng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB_UserMng.setPreferredSize(new java.awt.Dimension(180, 45));
        jP_MenuDesplegable.add(jB_UserMng);

        jB_Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image_Help.png"))); // NOI18N
        jB_Help.setText("  Ayuda");
        jB_Help.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB_Help.setPreferredSize(new java.awt.Dimension(180, 45));
        jP_MenuDesplegable.add(jB_Help);

        jB_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image-Logout.png"))); // NOI18N
        jB_LogOut.setText("Cerrar Sesión");
        jB_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB_LogOut.setPreferredSize(new java.awt.Dimension(180, 45));
        jP_MenuDesplegable.add(jB_LogOut);

        getContentPane().add(jP_MenuDesplegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 75, 185, 155));

        btn_AdministrarUsuarios.setBackground(new java.awt.Color(153, 255, 153));
        btn_AdministrarUsuarios.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn_AdministrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btn_AdministrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image-Ventas.png"))); // NOI18N
        btn_AdministrarUsuarios.setText("Administrar Usuarios");
        btn_AdministrarUsuarios.setContentAreaFilled(false);
        btn_AdministrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_AdministrarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_AdministrarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btn_AdministrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 170));

        btn_PedidoMateriaPrima.setBackground(new java.awt.Color(153, 255, 153));
        btn_PedidoMateriaPrima.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn_PedidoMateriaPrima.setForeground(new java.awt.Color(255, 255, 255));
        btn_PedidoMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image_MateriaPrima.png"))); // NOI18N
        btn_PedidoMateriaPrima.setText("Pedido Materia Prima");
        btn_PedidoMateriaPrima.setActionCommand("Venta");
        btn_PedidoMateriaPrima.setContentAreaFilled(false);
        btn_PedidoMateriaPrima.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_PedidoMateriaPrima.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_PedidoMateriaPrima.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btn_PedidoMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 200, 170));

        btn_Produccion.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn_Produccion.setForeground(new java.awt.Color(255, 255, 255));
        btn_Produccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Image_Produccion.png"))); // NOI18N
        btn_Produccion.setText("Producción");
        btn_Produccion.setContentAreaFilled(false);
        btn_Produccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Produccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btn_Produccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, 170));

        jLabel1_Up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Up_Welcome.png"))); // NOI18N
        getContentPane().add(jLabel1_Up, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jLabel2_FondoHelados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QDev/com/ImageSRC/Fondo_Welcome.jpg"))); // NOI18N
        getContentPane().add(jLabel2_FondoHelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, 780, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AdministrarUsuarios;
    private javax.swing.JButton btn_PedidoMateriaPrima;
    private javax.swing.JButton btn_Produccion;
    private javax.swing.JButton btn_closeMenu;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton jB_Help;
    private javax.swing.JButton jB_LogOut;
    private javax.swing.JButton jB_UserMng;
    private javax.swing.JLabel jLabel1_Up;
    private javax.swing.JLabel jLabel2_FondoHelados;
    private javax.swing.JLabel jLabel3_LogoFrutalito;
    private javax.swing.JLabel jLabel4_Titulo;
    private javax.swing.JPanel jP_MenuDesplegable;
    // End of variables declaration//GEN-END:variables

    public class OpenMenu implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            btn_menu.setVisible(false);
            btn_closeMenu.setVisible(true);
            jP_MenuDesplegable.setVisible(true);
            jB_Help.setVisible(true);
            jB_UserMng.setVisible(true);
            jB_LogOut.setVisible(true);

        }

    }

    public class CloseMenu implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            btn_menu.setVisible(true);
            btn_closeMenu.setVisible(false);
            jP_MenuDesplegable.setVisible(false);
            jB_Help.setVisible(false);
            jB_UserMng.setVisible(false);
            jB_LogOut.setVisible(false);
        }
    }

    public class LogOut implements ActionListener {

        //Inicalización Lazy
        private GUI_Login loginGUI = null;

        @Override
        public void actionPerformed(ActionEvent e) {

            //Cierra la ventana actual, siendo esta la de Admin.
            GUI_Admin.this.dispose();
            //Y se vuelve a abrir la ventana de Login, esencialmente
            //"cerrando la sesión".
            if (loginGUI == null) {
                loginGUI = new GUI_Login();
            }
            loginGUI.setVisible(true);
        }
    }

}
