/*
*   PROYECTO : ALERTAS TEMPRANAS DE BAJO RENDIMIENTO
*   Institucion: Universidad del Valle Sede Palmira
*   Autores:
*           Christian Joel Barbosa Bolaños 1958266-2711
*           Alejandro Castro Romero        1958283-2711
*           Keren Rodas Ortíz              1957601-2711
*           Leandro Rodriguez Vidal        1958205-2711
*
 */
package ventanas;

public class Icfes extends javax.swing.JFrame {

    /**
     * Creates new form Icfes
     */
    public Icfes() {
        initComponents();
        setTitle("Alertas Tempranas de Rendimiento - [Area Estudiante]");
        this.setLocationRelativeTo(null);
        setResizable(false);
        Panel_Options.setVisible(false); //El panel de las opciones no está visible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Return_Inicio = new javax.swing.JButton();
        Label_Titulo_Icfes = new javax.swing.JLabel();
        Label_Icfes_Math = new javax.swing.JLabel();
        Label_Icfes_LC = new javax.swing.JLabel();
        Label_Icfes_CN = new javax.swing.JLabel();
        Label_Icfes_SC = new javax.swing.JLabel();
        Label_Icfes_Ingles = new javax.swing.JLabel();
        Button_Menu_Opc = new javax.swing.JButton();
        Panel_Options = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel_FondoIcfes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Return_Inicio.setFont(new java.awt.Font("Segoe Print", 3, 22)); // NOI18N
        Button_Return_Inicio.setText("INICIO");
        Button_Return_Inicio.setToolTipText("Volver a Inicio");
        Button_Return_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Return_Inicio.setOpaque(false);
        Button_Return_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Return_InicioActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Return_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 40));

        Label_Titulo_Icfes.setFont(new java.awt.Font("Segoe Print", 3, 22)); // NOI18N
        Label_Titulo_Icfes.setText("PRUEBA: ICFES");
        getContentPane().add(Label_Titulo_Icfes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        Label_Icfes_Math.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Label_Icfes_Math.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Icfes_Math.setText("MATEMÁTICAS");
        Label_Icfes_Math.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Label_Icfes_Math.setOpaque(true);
        getContentPane().add(Label_Icfes_Math, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, 50));
        Label_Icfes_Math.getAccessibleContext().setAccessibleDescription("");

        Label_Icfes_LC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Label_Icfes_LC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Icfes_LC.setText("LECTURA CRÍTICA");
        Label_Icfes_LC.setToolTipText("");
        Label_Icfes_LC.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Label_Icfes_LC.setName(""); // NOI18N
        Label_Icfes_LC.setOpaque(true);
        getContentPane().add(Label_Icfes_LC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 200, 50));

        Label_Icfes_CN.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Label_Icfes_CN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Icfes_CN.setText("CIENCIAS NATURALES");
        Label_Icfes_CN.setOpaque(true);
        getContentPane().add(Label_Icfes_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 230, 50));

        Label_Icfes_SC.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Label_Icfes_SC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Icfes_SC.setText("SOCIALES / CIUDADANÍA");
        Label_Icfes_SC.setOpaque(true);
        getContentPane().add(Label_Icfes_SC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 260, 50));

        Label_Icfes_Ingles.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Label_Icfes_Ingles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Icfes_Ingles.setText("INGLÉS");
        Label_Icfes_Ingles.setOpaque(true);
        getContentPane().add(Label_Icfes_Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 100, 50));

        Button_Menu_Opc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DesplegableOpt.png"))); // NOI18N
        Button_Menu_Opc.setContentAreaFilled(false);
        Button_Menu_Opc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Menu_OpcMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Menu_Opc, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 30, -1));

        jButton2.setFont(new java.awt.Font("Segoe Print", 3, 10)); // NOI18N
        jButton2.setText("OPCIONES");
        jButton2.setOpaque(false);
        Panel_Options.add(jButton2);

        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 10)); // NOI18N
        jButton1.setText("CERRAR SESIÓN");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel_Options.add(jButton1);

        getContentPane().add(Panel_Options, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 130, 80));

        jLabel_FondoIcfes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icfes.png"))); // NOI18N
        getContentPane().add(jLabel_FondoIcfes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Return_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Return_InicioActionPerformed
        dispose(); //Desaparecer ventana 'Icfes'
        new Estudiantes_Area().setVisible(true); //Mostrar en pantalla ventana 'Inicio'
    }//GEN-LAST:event_Button_Return_InicioActionPerformed

    private void Button_Menu_OpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Menu_OpcMouseClicked
        Panel_Options.setVisible(true); //Mostrar en pantalla el panel de las opciones
    }//GEN-LAST:event_Button_Menu_OpcMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose(); //Desaparecer ventana 'Icfes'
        new Inicio().setVisible(true); //Mostrar en pantalla ventana 'Inicio'
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Menu_Opc;
    private javax.swing.JButton Button_Return_Inicio;
    private javax.swing.JLabel Label_Icfes_CN;
    private javax.swing.JLabel Label_Icfes_Ingles;
    private javax.swing.JLabel Label_Icfes_LC;
    private javax.swing.JLabel Label_Icfes_Math;
    private javax.swing.JLabel Label_Icfes_SC;
    private javax.swing.JLabel Label_Titulo_Icfes;
    private javax.swing.JPanel Panel_Options;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel_FondoIcfes;
    // End of variables declaration//GEN-END:variables
}
