/*
*   PROYECTO : ALERTAS TEMPRANAS DE BAJO RENDIMIENTO
*   Institucion: Universidad del Valle Sede Palmira
*   Autores:
*           Christian Joel Barbosa Bolaños 1958266-2711
*           Alejandro Castro Romero        1958283-2711
*           Keren Rodas Ortíz              1957601-2711
*           Leandro Rodriguez Vidal        1958205-2711
*
 */
package ventanas;

import BD.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static ventanas.Inicio.username;

public class Profesores_Area_Edicion_Notas extends javax.swing.JFrame {

    /**
     * Creates new form Profesores_Area_Edicion
     */
    public Profesores_Area_Edicion_Notas() {
        initComponents();
        setTitle("Alertas Tempranas de Rendimiento [Area Profesor]");
        this.setLocationRelativeTo(null);
        setResizable(false);
        jList1.setVisible(false);
        jScrollPane1.setVisible(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        Panel_Options.setVisible(false); //El panel de las opciones no está visible
    }

    //Traer nombre y apellido de la BD relacionados al usuario que ingresa:
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("atbr_proyecto?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        mMateriaQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM MMateria m");
        mMateriaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mMateriaQuery.getResultList();
        jLabel_SaludoProfesor = new javax.swing.JLabel();
        jLabel1_Salida_ElegirCurso = new javax.swing.JLabel();
        jTextField1_nombre_apellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Button_Menu_Opc = new javax.swing.JButton();
        Panel_Options = new javax.swing.JPanel();
        Button_Opciones = new javax.swing.JButton();
        Button_Cerrar_Sesión = new javax.swing.JButton();
        jLabel_FondoProfesores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_SaludoProfesor.setFont(new java.awt.Font("Segoe Print", 1, 22)); // NOI18N
        jLabel_SaludoProfesor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SaludoProfesor.setText("Bienvenido(a) Profesor(a)");
        getContentPane().add(jLabel_SaludoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jLabel1_Salida_ElegirCurso.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1_Salida_ElegirCurso.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Salida_ElegirCurso.setText("Elija el curso en el cual realizará las acciones:");
        getContentPane().add(jLabel1_Salida_ElegirCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextField1_nombre_apellido.setEditable(false);
        jTextField1_nombre_apellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1_nombre_apellido.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jTextField1_nombre_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_nombre_apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1_nombre_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 290, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MATERIAS");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 160, 40));

        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mMateriaList, jList1, "Materias");
        bindingGroup.addBinding(jListBinding);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jList1MouseExited(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 350, 180));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculo I");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel8.setText("Unidad 6. Derivada de una función ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, 20));

        jLabel9.setText("Unidad 5. Limites");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 330, 20));

        jLabel10.setText("Unidad 8. Principios de Integrales");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 370, 20));

        jLabel46.setText("Unidad 1. Números, funciones y gráficas");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 20));

        jLabel47.setText("Unidad 2. La Recta");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 20));

        jLabel48.setText("Unidad 3. Propiedades de los exponentes");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, 20));

        jLabel49.setText("Unidad 4. Propiedades de la radicación");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 330, 20));

        jLabel50.setText("Unidad 7. Aplicaciones de la Derivada");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 370, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingles I");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel11.setText("Sesión 16. Personal Interview (examen final Oral) Examen final escrito ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 180, -1));

        jLabel12.setText("Sesión 1.  Interview: Introducing yourself. Recognizing Word meanings");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, -1));

        jLabel13.setText("Sesión 2.  Company Facts and Figures. Simple Present");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, -1));

        jLabel14.setText("Sesión 3.  Talking about the Company.Present Progressive");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, -1));

        jLabel15.setText("Sesión 4.  Describing Company Projects: Possessive Adjectives. Stems and Affixes");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        jLabel16.setText("Sesión 5.  Franchising (lectura) Skimming and Scanning. Adverbs of Frequency");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, -1));

        jLabel17.setText("Sesión 6.  Telephoning. Getting through, making arrangements, checking information. Role Play");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 290, -1));

        jLabel18.setText("Sesión 7.  Prepositions for Time and Place. Word stress. Contextual references");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, -1));

        jLabel19.setText("Sesión 8.  Colombian Franchises (exposición) Examen escrito (parcial)");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, -1));

        jLabel20.setText("Sesión 9.  Recognizing Cognates. Intensive Reading. Understanding Non-linear texts");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, -1));

        jLabel21.setText("Sesión 10. Cultural Aspects. Countable and Uncountable Nouns. Compound Words");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, -1));

        jLabel22.setText("Sesión 11. Multinational Companies. Critical Reading.");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 270, -1));

        jLabel23.setText("Sesión 12. Doing Business Making Money. Differences in the use of Do and Make.");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 180, -1));

        jLabel24.setText("Sesión 13. Conducting a Meeting. Telling the time. Role Play");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 180, -1));

        jLabel25.setText("Sesión 14. Gerund and Infinitive Verbs. Coca-Cola Company History");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 180, -1));

        jLabel26.setText("Sesión 15. Object Pronouns. Regional accents.");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Español I");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel27.setText("Tema 12. La cohesión y la coherencia");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel28.setText("Tema 1.  Nuestra Historia como lectores");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel29.setText("Tema 2.  La producción de Textos");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel30.setText("Tema 3. Los géneros discursivos y los tipos de textos");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel31.setText("Tema 4. Los Textos expositivos");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel32.setText("Tema 5. Artículo de divulgación científica.");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel33.setText("Tema 6. Los textos narrativos ");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel34.setText("Tema 7. Los textos narrativos ");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel35.setText("Tema 8. Los textos narrativos ");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel36.setText("Tema 9. El Resumen");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel37.setText("Tema 10. La reseña critica");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel38.setText("Tema 11. La argumentación Tipos de argumentos ");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Deporte Formativo");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel39.setText("Tema 7. Tests de fuerza");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel40.setText("Tema 1. Historia del deporte");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel41.setText("Tema 2. Estiramientos");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel42.setText("Tema 3. Carreras");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel43.setText("Tema 4. Calistemia");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel44.setText("Tema 5. Beneficios del deporte");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel45.setText("Tema 6. Tests de resistencia");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fundamentos de Programación");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel51.setText("Tema 13. Estructuras");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 180, -1));

        jLabel52.setText("Tema 1. Historia de la programación");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel53.setText("Tema 2. Lenguajes de Programación");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jLabel54.setText("Tema 3. Dr Racket");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jLabel55.setText("Tema 4. Definición de Variables");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, -1));

        jLabel56.setText("Tema 5. Problemas Simples");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, -1));

        jLabel57.setText("Tema 6. Precedencia de operadores");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jLabel58.setText("Tema 7. Declaración de Constantes");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jLabel59.setText("Tema 8. Sentencias Condicionales");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, -1));

        jLabel60.setText("Tema 9. Sentencias Repetitivas");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, -1));

        jLabel61.setText("Tema 10. Listas");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, -1));

        jLabel62.setText("Tema 11. Recursividad");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, -1));

        jLabel63.setText("Tema 12. Arboles");
        jPanel5.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 180, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Introducción a la Tecnología de Información");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel64.setText("Tema 8. Repositorios");
        jPanel6.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel65.setText("Tema 1. Historia del Computador");
        jPanel6.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel66.setText("Tema 2. Procesadores de texto");
        jPanel6.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel67.setText("Tema 3. Procesadores de graficas");
        jPanel6.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel68.setText("Tema 4. Hojas de Calculo");
        jPanel6.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel69.setText("Tema 5. Bases de Datos");
        jPanel6.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel70.setText("Tema 6. Tipos de Malware");
        jPanel6.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel71.setText("Tema 7. Tipos de Conexiones a la red");
        jPanel6.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel72.setText("Tema 8. Fundamentos de PSeInt");
        jPanel6.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel73.setText("Tema 8. Herramientas de Comunicación");
        jPanel6.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Teoria General de Sistemas");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 30));

        jLabel75.setText("Tema 1. Conceptos de TGS");
        jPanel7.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel76.setText("Tema 2. Metodos de investigación");
        jPanel7.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel77.setText("Tema 3. Normas APA, IEEE");
        jPanel7.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel78.setText("Tema 4. Implementacion de la TGS");
        jPanel7.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel79.setText("Tema 5. Sistemas Blandos y Duros");
        jPanel7.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 540, 290));

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 100, 40));

        Button_Menu_Opc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DesplegableOpt.png"))); // NOI18N
        Button_Menu_Opc.setContentAreaFilled(false);
        Button_Menu_Opc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Menu_OpcMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Menu_Opc, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 30, -1));

        Button_Opciones.setFont(new java.awt.Font("Segoe Print", 3, 10)); // NOI18N
        Button_Opciones.setText("OPCIONES");
        Button_Opciones.setOpaque(false);
        Panel_Options.add(Button_Opciones);

        Button_Cerrar_Sesión.setFont(new java.awt.Font("Segoe Print", 3, 10)); // NOI18N
        Button_Cerrar_Sesión.setText("CERRAR SESIÓN");
        Button_Cerrar_Sesión.setOpaque(false);
        Button_Cerrar_Sesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Cerrar_SesiónActionPerformed(evt);
            }
        });
        Panel_Options.add(Button_Cerrar_Sesión);

        getContentPane().add(Panel_Options, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 130, 80));

        jLabel_FondoProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoProfesores.png"))); // NOI18N
        getContentPane().add(jLabel_FondoProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

//no tocar-------------------------------------------------------------------------------------------------
    private void jTextField1_nombre_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_nombre_apellidoActionPerformed

    }//GEN-LAST:event_jTextField1_nombre_apellidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jScrollPane1.setVisible(true);
        jList1.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jList1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseExited
        jScrollPane1.setVisible(false);
        jList1.setVisible(false);
    }//GEN-LAST:event_jList1MouseExited

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

    }//GEN-LAST:event_jList1ValueChanged

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        //Calculo I
        if (jList1.getSelectedIndex() == 0) {
            jPanel1.setVisible(true);

            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            jPanel7.setVisible(false);

        }
        //Ingles I
        if (jList1.getSelectedIndex() == 1) {
            jPanel2.setVisible(true);

            jPanel1.setVisible(false);

            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            jPanel7.setVisible(false);
        }
        //Español I
        if (jList1.getSelectedIndex() == 2) {
            jPanel3.setVisible(true);

            jPanel1.setVisible(false);
            jPanel2.setVisible(false);

            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            jPanel7.setVisible(false);
        }
        //Deporte Formativo
        if (jList1.getSelectedIndex() == 3) {
            jPanel4.setVisible(true);

            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);

            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            jPanel7.setVisible(false);
        }
        //Fundamentos de Programación
        if (jList1.getSelectedIndex() == 4) {
            jPanel5.setVisible(true);

            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);

            jPanel6.setVisible(false);
            jPanel7.setVisible(false);
        }
        //Introduccion a la Tecnología de información
        if (jList1.getSelectedIndex() == 5) {
            jPanel6.setVisible(true);

            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);

            jPanel7.setVisible(false);

        }
        //Teoría General de Sistemas
        if (jList1.getSelectedIndex() == 6) {
            jPanel7.setVisible(true);

            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void Button_Cerrar_SesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Cerrar_SesiónActionPerformed
        dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_Button_Cerrar_SesiónActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //Calculo I
        if (jList1.getSelectedIndex() == 0 && (!username.equals("35791357"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }

        if (jList1.getSelectedIndex() == 0 && username.equals("35791357")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);
//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
        }

        //Ingles I
        if (jList1.getSelectedIndex() == 1 && (!username.equals("32842001"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }
        if (jList1.getSelectedIndex() == 1 && username.equals("32842001")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);

//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================            
        }

        //Español I
        if (jList1.getSelectedIndex() == 2 && (!username.equals("44467912"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }
        if (jList1.getSelectedIndex() == 2 && username.equals("44467912")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);
//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================            
        }

        //Deporte Formativo
        if (jList1.getSelectedIndex() == 3 && (!username.equals("46813579"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }
        if (jList1.getSelectedIndex() == 3 && username.equals("46813579")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);
//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================            
        }

        //Fundamentos de Programación
        if (jList1.getSelectedIndex() == 4 && (!username.equals("26280496"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }
        if (jList1.getSelectedIndex() == 4 && username.equals("26280496")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);
//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================            
        }
        //Introduccion a la Tecnología de información
        if (jList1.getSelectedIndex() == 5 && (!username.equals("26280496"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }
        if (jList1.getSelectedIndex() == 5 && username.equals("26280496")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);
//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================            
        }

        //Teoría General de Sistemas
        if (jList1.getSelectedIndex() == 6 && (!username.equals("22639751"))) {
            JOptionPane.showMessageDialog(null, "Usted no es el profe de esta materia");
        }
        if (jList1.getSelectedIndex() == 6 && username.equals("22639751")) {
            dispose();
            new ventanas.newpackagePROFESORES.Edicion().setVisible(true);
//======================================================================================================================
//Para sacar el nombre y apellido del profesor actual
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre, apellido FROM `m_profesor` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String apellido = rss.getNString("apellido");
                    String nombreApeP = nombre + apellido;
                    ventanas.newpackagePROFESORES.Edicion.jTextField1_nombre_apellido.setText(nombreApeP);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================
//Para sacar el nombre de la materia seleccionada
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "SELECT nombre FROM `m_materia` WHERE idProfesor='" + username + "'");
                //Ejecutar la Sentencia SQL con el Objeto ResultSet:
                ResultSet rss = ps.executeQuery();
                if (rss.next()) {
                    String nombre = rss.getNString("nombre");
                    String nombreMateria = nombre;
                    ventanas.newpackagePROFESORES.Edicion.nombreMateria.setText(nombreMateria);
                }
            } catch (SQLException e) {
                System.out.println("Error de BD" + e);
            }
//======================================================================================================================            
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void Button_Menu_OpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Menu_OpcMouseClicked
        Panel_Options.setVisible(true); //Mostrar en pantalla el panel de las opciones
    }//GEN-LAST:event_Button_Menu_OpcMouseClicked
//fin no tocar----------------------------------------------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cerrar_Sesión;
    private javax.swing.JButton Button_Menu_Opc;
    private javax.swing.JButton Button_Opciones;
    private javax.swing.JPanel Panel_Options;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1_Salida_ElegirCurso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_FondoProfesores;
    private javax.swing.JLabel jLabel_SaludoProfesor;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField1_nombre_apellido;
    private java.util.List<BD.MMateria> mMateriaList;
    private javax.persistence.Query mMateriaQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
